services:
  - type: web
    name: online-voting-system
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: MONGO_URI
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: MAIL_EMAIL
        sync: false
      - key: MAIL_PASSWORD
        sync: false